kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-backup-pvc
  namespace: ocp-etcd-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: <storageclass-name>
  resources:
    requests:
      storage: 10Gi # Adjust this value according to your needs
